version: "3.9"

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
        context: .
        dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
    container_name: php
    ports:
      ["9000:9000", "9003:9003"]
    expose:
      ["9000", "9003"]
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:lts-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    ports:
      - "5173:5173"
    expose:
      - "5173"
    networks:
      - laravel